// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.DbContexts;

namespace WebAPI.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20201117220623_CreateClienteDomicilioPagoReciboTables")]
    partial class CreateClienteDomicilioPagoReciboTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10");

            modelBuilder.Entity("WebAPI.Models.Cliente", b =>
                {
                    b.Property<int>("Cuenta")
                        // .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellidos")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaveDeLocalizacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("Contrato")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("TEXT");

                    b.Property<int>("DomicilioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Medidor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombres")
                        .HasColumnType("TEXT");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rfc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.HasKey("Cuenta");

                    b.HasIndex("DomicilioId")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("WebAPI.Models.Domicilio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CalleA")
                        .HasColumnType("TEXT");

                    b.Property<string>("CalleB")
                        .HasColumnType("TEXT");

                    b.Property<string>("CallePrincipal")
                        .HasColumnType("TEXT");

                    b.Property<int>("CodigoPostal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Colonia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Localidad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Municipio")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroExterior")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumeroInterior")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Domicilios");
                });

            modelBuilder.Entity("WebAPI.Models.Pago", b =>
                {
                    b.Property<int>("Folio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Autorizacion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(200);

                    b.Property<DateTime>("FechaDePago")
                        .HasColumnType("TEXT");

                    b.Property<double>("Importe")
                        .HasColumnType("REAL");

                    b.Property<string>("NombreDelTitular")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<string>("Tarjeta")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.HasKey("Folio");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("WebAPI.Models.Recibo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Bomberos")
                        .HasColumnType("REAL");

                    b.Property<int>("ClienteCuenta")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Consumo")
                        .HasColumnType("REAL");

                    b.Property<int>("ConsumoEnM3")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CruzRoja")
                        .HasColumnType("REAL");

                    b.Property<double>("Drenaje")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("FechaDeInicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaDeLectura")
                        .HasColumnType("TEXT");

                    b.Property<double>("ImporteTotal")
                        .HasColumnType("REAL");

                    b.Property<int>("LecturaActual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LecturaAnterior")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MesesDeAdeudo")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Multas")
                        .HasColumnType("REAL");

                    b.Property<int>("PagoFolio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PeriodoDeFacturacion")
                        .HasColumnType("TEXT");

                    b.Property<double>("Recargos")
                        .HasColumnType("REAL");

                    b.Property<double>("Saneamiento")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ClienteCuenta");

                    b.HasIndex("PagoFolio")
                        .IsUnique();

                    b.ToTable("Recibos");
                });

            modelBuilder.Entity("WebAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(200);

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(16);

                    b.Property<string>("RememberToken")
                        .HasColumnType("TEXT")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebAPI.Models.Cliente", b =>
                {
                    b.HasOne("WebAPI.Models.Domicilio", "Domicilio")
                        .WithOne("Cliente")
                        .HasForeignKey("WebAPI.Models.Cliente", "DomicilioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebAPI.Models.Recibo", b =>
                {
                    b.HasOne("WebAPI.Models.Cliente", "Cliente")
                        .WithMany("Recibos")
                        .HasForeignKey("ClienteCuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI.Models.Pago", "Pago")
                        .WithOne("Recibo")
                        .HasForeignKey("WebAPI.Models.Recibo", "PagoFolio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
